[tool.ruff]
target-version = "py310"
line-length = 120
exclude = [".venv"]
indent-width = 4

[tool.ruff.lint]
# Rules list: https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "ANN101", # The rule has been deprecated since ruff 0.2.0.
    "ANN102", # The rule has been deprecated since ruff 0.2.0.
    "ANN401", # typing.Any is allowed in special cases caused by external packages.
    "RET504", # For easier debug and better code readability this rule is disabled.
    "FIX002", # TODOs are allowed during developement process.
    "TD002", # Link to issue should already assigne author.
    "D401", # Imperative mood in function description is not required.
    "UP032", # Doesnt work in some cases.
    "PTH", # Pathlib is not required.
    "TCH002", # Type hinting section in import sorting is not required.

    # Below rules has conflict with formatting and should be disabled.
    # Docs with explantion: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules.
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 120
