[tool.ruff]
target-version = "py310"
line-length = 120
exclude = [".venv"]
indent-width = 4

[tool.ruff.lint]
# Rules list: https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "RET504", # For easier debug and better code readability this rule is disabled.
    "ANN101", # The rule has been deprecated since ruff 0.2.0.
    "ANN102", # The rule has been deprecated since ruff 0.2.0.
    "TD002", # Link to issue should already assigne author.
    "COM812", # Conflict with ruff format.
    "ISC001", # Conflict with ruff format.
    "E501", # Line too long, handled by ruff format.
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.ruff.lint.per-file-ignores]
# Ignore rules on tests.
"tests/**" = [
    "D", # Exclude docstring checks on tests.
    "S101", # Allow asserts in tests.
    "ANN201", # Disable return types in tests.
]